api_version = "2024-10"

[[extensions]]
type = "theme_app_extension"
name = "Loyco Loyalty Blocks"
handle = "loyco-loyalty-blocks"

[extensions.settings]
[[extensions.settings.blocks]]
type = "loyalty_customer_status"
name = "Customer Loyalty Status"
settings = [
  {
    type = "text",
    id = "heading",
    label = "Heading",
    default = "Your Loyalty Status"
  },
  {
    type = "checkbox",
    id = "show_points",
    label = "Show Points Balance",
    default = true
  },
  {
    type = "checkbox",
    id = "show_tier",
    label = "Show Current Tier",
    default = true
  },
  {
    type = "checkbox",
    id = "show_progress",
    label = "Show Tier Progress",
    default = true
  },
  {
    type = "color",
    id = "primary_color",
    label = "Primary Color",
    default = "#6366f1"
  }
]

[[extensions.settings.blocks]]
type = "loyalty_rewards_grid"
name = "Available Rewards"
settings = [
  {
    type = "text",
    id = "heading",
    label = "Heading",
    default = "Available Rewards"
  },
  {
    type = "range",
    id = "rewards_limit",
    label = "Number of Rewards to Show",
    min = 1,
    max = 12,
    step = 1,
    default = 6
  },
  {
    type = "checkbox",
    id = "show_points_required",
    label = "Show Points Required",
    default = true
  },
  {
    type = "color",
    id = "accent_color",
    label = "Accent Color",
    default = "#f59e0b"
  }
]

[[extensions.settings.blocks]]
type = "loyalty_product_points"
name = "Product Points Indicator"
settings = [
  {
    type = "text",
    id = "text_template",
    label = "Points Text Template",
    default = "Earn {points} points with this purchase"
  },
  {
    type = "checkbox",
    id = "show_tier_multiplier",
    label = "Show Tier Multiplier",
    default = true
  },
  {
    type = "select",
    id = "position",
    label = "Position",
    options = [
      { value = "above_price", label = "Above Price" },
      { value = "below_price", label = "Below Price" },
      { value = "above_buttons", label = "Above Add to Cart" },
      { value = "below_buttons", label = "Below Add to Cart" }
    ],
    default = "below_price"
  }
]