[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "loyco-rewards-app"

[services.variables]
NODE_ENV = "production"
PORT = { default = 3000 }

[[services]]
name = "postgres"
type = "database"

[services.config]
plan = "shared"
size = "10GB"
backups = true

[[services]]
name = "redis"
type = "redis"

[services.config]
plan = "shared"
size = "1GB"
persistence = true